---
title: Hotkey and Remap
---
classDiagram
direction TB
    class FileAccess {
	    ファイルのアクセス
    }
    class HotkeyAndRemapMapLoader {
      hotkeyとremapのマップのロード、トリガーの判定(vkによる判定処理)、アクションの実行
    }
    class KeyMapLoader {
      vkとキーネームのmap
    }
    class KeyboardHookManager {
    SetWindowHookExでキー全体にフック
    }
    class HotkeyActionFuncs {
      hotkeyの実行関数定義
    }
    class RemapActionFuncs {
      remapの実行関数定義
    }
    class Logger {
      debug関数の定義
    }
    class Utils {
      Utility関数の定義
    }
    class Types {
      構造体や名前空間の定義
    }
    class main {
      mainファイル
    }
  
    FileAccess <|-- HotkeyAndRemapMapLoader
    KeyMapLoader <|-- HotkeyAndRemapMapLoader
    KeyboardHookManager<|-- RemapActionFuncs
    RemapActionFuncs<|-- HotkeyAndRemapMapLoader
    HotkeyActionFuncs <|-- HotkeyAndRemapMapLoader
    HotkeyAndRemapMapLoader <|-- main
    Logger <|-- FileAccess
    Utils <|-- FileAccess
    Types <|-- Utils