"""add unique constraint to user_roles(session_id, sequence_id)

Revision ID: bbe910d06b18
Revises: e1e335f6f3fd
Create Date: 2025-08-16 08:17:42.179909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbe910d06b18'
down_revision: Union[str, Sequence[str], None] = 'e1e335f6f3fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('keylogs_session_id_sequence_id_key', 'keylogs', ['session_id', 'sequence_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('keylogs_session_id_sequence_id_key', 'keylogs', type_='unique')
    # ### end Alembic commands ###
