import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import { Orbitron, Audiowide, Exo_2, Inter, Noto_Sans} from "next/font/google";

export const metadata: Metadata = {
  title: "Visualizaiton for Keylog",
  description: "Generated by create next app",
};

const orbitron = Orbitron({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-orbitron",
});
const audiowide = Audiowide({
  subsets: ["latin"],
  weight: "400", // Audiowide は 400 のみ
  variable: "--font-audiowide", // CSS変数として登録
});
const exo_2 = Exo_2({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-exo_2",
});
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const noto_sans = Noto_Sans({
  subsets: ["latin"],
  variable: "--font-noto_sans",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={`${orbitron.variable} ${audiowide.variable} ${exo_2.variable} ${inter.variable} ${noto_sans.variable} font-sans`}>
        {/* <React.StrictMode> */}
          {children}
        {/* </React.StrictMode> */}
      </body>
    </html>
  );
}
